### ISSUE TITLE
Turn "handleSubmit" into a component function

### ISSUE THREAD

**Issue by martinheidegger** [AndrewZamora/react-login-form#2]
The "handleSubmit" action in the component is handled directly in the component:

https://github.com/AndrewZamora/react-login-form/blob/0dc28aefe0ba201296de24f2659910130b81fad8/src/components/Login.js#L18-L22

In order for the component to be re-used the logic should be handled outside:

```jsx
<Login onLogin=""/>
```

At this point you have to think about the control flow:

```
<A. Someone clicks Login button> → <B. Login Request to Server> → <C. UI reacts>
```

How could an API for this look like? Here is my shot:

```jsx
const login = <Login onSubmit={onSubmit}>

function onSubmit (user, password) {
   console.log(login.isLoggingIn) // true
   return new Promise((resolve, reject) => {
     resolve() // will mark the login attempt as successful.
     reject(new LoginUserError()) // will show a login error
   })
}
```

_Note: After #1_

**Comment by AndrewZamora** [comment]
Can I achieve what you are talking about with a higher order component?

**Comment by martinheidegger** [comment]
It can be achieved using a higher-order component but that would be a future step, lets keep it simple for now 😉

**Comment by martinheidegger** [comment]
@AndrewZamora PR's that are not finished are `WIP`(Work in Progress). So just make a PR and prefix the title with "[WIP] ...."

**Comment by AndrewZamora** [comment]
@martinheidegger Thank you for the `WIP` tip 👍 I think I don't completely catch what you are saying at the beginning of the issue.  By "logic should be handled outside" do you mean move the "handleSubmit" function? If so do I put it in the `App.js` file and pass it down through props or put it in the `Login.js` file above where it says, `class Login extends Component`? I think what is throwing me off is that I'm not sure where to put the following:
```javascript
function onSubmit (user, password) {
   console.log(login.isLoggingIn) // true
   return new Promise((resolve, reject) => {
     resolve() // will mark the login attempt as successful.
     reject(new LoginUserError()) // will show a login error
   })
}
```
